const assert = require('assert');
const round = require('./round');

const items = [
    [34, 25, 25],
    [37.5, 25, 50],
    [34.037531, 0.001, 34.038],
    [1.005, 0.01, 1.01],
    [0.99999, 0.00001, 0.99999],

    // Synthetic cases generated by DeepSeek
    [1.005, 0.001, 1.005],        // More precise rounding
    [1.005, 0.1, 1.0],            // Less precise rounding
    [1.015, 0.01, 1.02],          // Another edge case with 5
    [1.025, 0.01, 1.03],          // Yet another edge case
    [0.5, 1, 1],                  // Round to nearest integer
    [0.4, 1, 0],                  // Round down to integer
    [123.456, 0.01, 123.46],      // Standard decimal rounding
    [123.456, 0.1, 123.5],        // Different precision
    [123.456, 1, 123],            // Round to whole number
    [123.456, 10, 120],           // Round to tens
    [123.456, 100, 100],          // Round to hundreds
    [0, 0.01, 0],                 // Zero value
    [-1.005, 0.01, -1.01],        // Negative numbers
    [-1.015, 0.01, -1.02],        // Negative edge case
    [-37.5, 25, -50],             // Negative with integer precision
    [1.2345e-5, 1e-6, 0.000012],  // Very small numbers
    [999.999, 0.001, 999.999],    // Rounding that causes carry-over
    [0.0000000000001, 0.01, 0],   // Extremely small number
    [Number.MAX_SAFE_INTEGER, 1000, 9007199254741000], // Large numbers

    [0.005, 0.01, 0.01],
    [-1.5, 1, -2],                          // Symmetric negative rounding (Math.abs is critical here)
    [-0.5, 1, -1],                          // Symmetric negative rounding for half
    [123456789123.45, 1000, 123456789000],  // Testing very large numbers
    [1.2345e-20, 1e-20, 1e-20],             // Testing very small numbers
    [1.0000000000000001, 0.0000000000000001, 1.0000000000000000], // Testing rounding near Number.EPSILON range

    [9007199254740992, 1, 9007199254740992],
    [9007199254740991.5, 1, 9007199254740992],
    [Number.MIN_SAFE_INTEGER, 1, Number.MIN_SAFE_INTEGER],
    [Number.MAX_SAFE_INTEGER, 1, Number.MAX_SAFE_INTEGER],

    // Out of scope of standard JS
    // [0.004999999999999999, 0.01, 0.0],
    // [Number.MIN_SAFE_INTEGER, 0.1, Number.MIN_SAFE_INTEGER],
    // [Number.MAX_SAFE_INTEGER, 0.1, Number.MAX_SAFE_INTEGER],
];

describe('round', function () {
    items.forEach(function ([value, precision, expected],) {
        it(`${value} [${precision}] → ${expected}`, function () {
            assert.deepStrictEqual(round(value, precision), expected);
        });
    });
});
